
# Do chuyển sang docker swarm nên file docker-compose.yml này sẽ không còn sử dụng nữa
# Sử dụng docker-stack để thay thế

services:
  mongodb:
      image: mongo:7
      container_name: noteweb-mongodb
      restart: unless-stopped
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin123
      volumes:
        - mongo_data:/data/db
        - ./mongo-init:/docker-entrypoint-initdb.d
        - ./dump:/dump

  backend:
    build:
      context: .
      dockerfile: backend/dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - monitor-net
      - MONGODB_URI: mongodb://admin:admin123@mongodb:27017/?authSource=admin
    depends_on:
      - otel-collector
      - mongodb

  frontend:
    build:
      context: .
      dockerfile: frontend/dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data: