version: "3.9"

services:

  backend:
    image: dangwminh/backend:${IMAGE_TAG}

    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      CLOUDY_NAME: ${CLOUDY_NAME}
      CLOUDY_API_KEY: ${CLOUDY_API_KEY}
      CLOUDY_SECRET: ${CLOUDY_SECRET}
      GG_CLIENT_ID: ${GG_CLIENT_ID}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317

    networks:
      app-network:
        aliases:
          - backend

    deploy:
      replicas: 3

      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M 

      update_config:
        parallelism: 1
        order: start-first

  frontend:
    image: dangwminh/frontend:${IMAGE_TAG}

    networks:
      app-network:
        aliases:
          - frontend

    deploy:
      replicas: 2

      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

      update_config:
        parallelism: 1
        order: start-first

  nginx:
    image: nginx:latest

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /etc/nginx/conf.d/default.conf
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt

    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf

    networks:
      app-network:
        aliases:
          - nginx

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  mongo:
    image: mongo:7

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

    volumes:
      - mongo_data:/data/db

    networks:
      app-network:
        aliases:
          - mongo

    deploy:
      replicas: 1
      restart_policy:
            condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  node-exporter:
    image: prom/node-exporter:latest
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - app-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - app-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    configs:
      - source: otel_config
        target: /etc/otel_config.yaml
    command: ["--config=/etc/otel_config.yaml"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: noteweb-net

volumes:
  mongo_data:

configs:
  nginx_config:
    name: nginx_config_${IMAGE_TAG}
    file: ./nginx.conf
  otel_config:
    file: ./monitoring/otel_config.yaml
