version: "3.9"

services:

  backend:
    image: dangwminh/backend:${IMAGE_TAG}

    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      CLOUDY_NAME: ${CLOUDY_NAME}
      CLOUDY_API_KEY: ${CLOUDY_API_KEY}
      CLOUDY_SECRET: ${CLOUDY_SECRET}
      GG_CLIENT_ID: ${GG_CLIENT_ID}

    networks:
      - app-network

    deploy:
      replicas: 3

      update_config:
        parallelism: 1
        order: start-first

  frontend:
    image: dangwminh/frontend:${IMAGE_TAG}

    networks:
      - app-network

    deploy:
      replicas: 2

      update_config:
        parallelism: 1
        order: start-first

  nginx:
    image: nginx:latest

    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    networks:
      - app-network

    deploy:
      replicas: 1

  mongo:
    image: dangwminh/mongo-init:${IMAGE_TAG}

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

    volumes:
      - mongo_data:/data/db

    networks:
      - app-network

    deploy:
      replicas: 1

networks:
  app-network:

volumes:
  mongo_data:
