server {
    listen 80;
    server_name _;

    resolver 127.0.0.11 valid=30s ipv6=off; # docker internal DNS resolver for service discovery

    location / {
        proxy_pass http://frontend:80;
    }

    location /api/ {
        proxy_pass http://backend:8000/;
    }
}