# ===== 1. Build stage =====
FROM node:20 AS build

WORKDIR /app

# copy package files truoc de tan dung cache
COPY apps/frontend/package*.json ./
RUN npm install

# copy source code
COPY apps/frontend ./

# build
RUN npm run build


# ===== 2. Serve stage =====
FROM nginx:alpine

# copy CRA build output sang nginx
COPY --from=build /app/build /usr/share/nginx/html
COPY apps/frontend/nginx.conf /etc/nginx/conf.d/default.conf

# expose port
EXPOSE 80

# chay nginx
CMD ["nginx", "-g", "daemon off;"]
