# ===== 1. Build stage =====
FROM node:20 AS build

WORKDIR /app

COPY apps/frontend/package*.json ./

RUN npm ci

COPY apps/frontend .

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build


# ===== 2. Serve stage =====
FROM nginx:alpine

RUN apk update && apk upgrade --no-cache

COPY --from=build /app/build /usr/share/nginx/html

COPY apps/frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]