services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    configs:
      prometheus_config:
        file: ./prometheus.yml
      alert_rules:
        file: ./alert_rules.yml
      grafana_datasource:
        file: ./grafana/datasources/datasource.yml
    volumes:
      - prometheus_data:/prometheus
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - noteweb-net

  grafana:
    image: grafana/grafana:latest
    configs:
      - source: grafana_datasource
        target: /etc/grafana/provisioning/datasources/datasource.yml
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_password
    secrets:
      - grafana_password
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - noteweb-net

configs:
  prometheus_config:
    file: ./prometheus.yml
  alert_rules:
    file: ./alert_rules.yml

networks:
  noteweb-net:
    external: true
    name: noteweb-net

volumes:
  prometheus_data:
  grafana_data:

secrets:
  grafana_password:
    external: true