global:
  scrape_interval: 15s

scrape_configs:
  # 1. Lấy dữ liệu CPU/RAM máy chủ từ Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # 2. Lấy dữ liệu chi tiết từng container từ cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # 3. Lấy dữ liệu nghiệp vụ (Business Metrics) từ OTel Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']