services:
  backend:
    build:
      context: ../..
      dockerfile: apps/backend/dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../..
      dockerfile: apps/frontend/dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
