[manager]
54.169.183.229

[workers]
47.129.174.188
47.128.223.17
13.212.34.102

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/key-terra.pem
domain_name=dangtm.pro
email=tonminhdang9@gmail.com