- hosts: all
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    

# =========================
# SWARM INIT (MANAGER ONLY)
# =========================
- hosts: manager
  become: yes

  tasks:
    - name: Check swarm state
      shell: docker info --format '{{ "{{.Swarm.LocalNodeState}}" }}'
      register: swarm_state
      changed_when: false

    - name: Init swarm
      shell: docker swarm init
      when: swarm_state.stdout != "active"

    - name: Get worker token
      shell: docker swarm join-token -q worker
      register: worker_token
      changed_when: false

    - name: Save token
      set_fact:
        swarm_token: "{{ worker_token.stdout }}"

# =========================
# WORKERS JOIN SWARM
# =========================
- hosts: workers
  become: yes

  tasks:
    - name: Leave old swarm if exists
      shell: docker swarm leave --force
      ignore_errors: yes

    - name: Join swarm
      shell: >
        docker swarm join
        --token {{ hostvars[groups['manager'][0]].swarm_token }}
        {{ hostvars[groups['manager'][0]].ansible_host | default(groups['manager'][0]) }}:2377

# =========================
# TRAEFIK & APP DEPLOY (MANAGER ONLY)
# =========================
- hosts: manager
  become: yes

  tasks:
    - name: Create overlay network
      shell: docker network create -d overlay noteweb-net || true

    - name: Create traefik acme dir
      file:
        path: /opt/traefik
        state: directory                             

    - name: Create acme file
      file:
        path: /opt/traefik/acme.json
        state: touch
        mode: '600'

    - name: Check Traefik exists
      shell: docker service ls -q --filter name=traefik
      register: trf_check
      changed_when: false

    - name: Check Traefik exists
      shell: docker service ls -q --filter name=traefik
      register: trf_check
      changed_when: false

    - name: Deploy Traefik (HTTPS layer)
      shell: |
        echo "[1/4] Deploying Traefik..."

        docker service create \
          --name traefik \
          --constraint=node.role==manager \
          --publish 80:80 \
          --publish 443:443 \
          --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
          --mount type=bind,source=/opt/traefik/acme.json,target=/acme.json \
          --network noteweb-net \
          traefik:v3 \
          --providers.docker=true \
          --providers.swarm=true \
          --providers.docker.exposedbydefault=false \
          --entrypoints.web.address=:80 \
          --entrypoints.websecure.address=:443 \
          --entrypoints.web.http.redirections.entrypoint.to=websecure \
          --certificatesresolvers.le.acme.httpchallenge=true \
          --certificatesresolvers.le.acme.httpchallenge.entrypoint=web \
          --certificatesresolvers.le.acme.email=tonminhdang9@gmail.com \
          --certificatesresolvers.le.acme.storage=/acme.json

        echo "[2/4] Traefik created"
        echo "[3/4] Waiting for service..."
        sleep 5
        echo "[4/4] Done"


    # - name: Wait Traefik running
    #   shell: docker service ps traefik --filter "desired-state=running" --format "{{.CurrentState}}"
    #   register: trf_state
    #   retries: 20
    #   delay: 5
    #   until: trf_state.stdout is search("Running")