- hosts: all
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

# =========================
# SWARM INIT (MANAGER ONLY)
# =========================
- hosts: manager
  become: yes

  tasks:
    - name: Check swarm state
      shell: docker info --format '{{ "{{.Swarm.LocalNodeState}}" }}'
      register: swarm_state
      changed_when: false

    - name: Init swarm
      shell: docker swarm init
      when: swarm_state.stdout != "active"

    - name: Get worker token
      shell: docker swarm join-token -q worker
      register: worker_token
      changed_when: false

    - name: Save token
      set_fact:
        swarm_token: "{{ worker_token.stdout }}"

# =========================
# WORKERS JOIN SWARM
# =========================
- hosts: workers
  become: yes

  tasks:
    - name: Leave old swarm if exists
      shell: docker swarm leave --force
      ignore_errors: yes

    - name: Join swarm
      shell: >
        docker swarm join
        --token {{ hostvars[groups['manager'][0]].swarm_token }}
        {{ hostvars[groups['manager'][0]].ansible_host | default(groups['manager'][0]) }}:2377