name: Backend CD

on:
  push:
      branches:
        - main
        - Test/cicd-test
  workflow_dispatch:

jobs:

  backend:
    runs-on: ubuntu-latest

    steps:

      - name: "[INFO - General] Checkout"
        uses: actions/checkout@v4

      - name: "[INFO - General] Login Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: "[INFO - Backend] Build backend"
        run: |
          docker build \
            -t dangwminh/backend:${{ github.sha }} \
            ./backend

      - name: "[INFO - Backend] Push backend"
        run: |
          docker push dangwminh/backend:${{ github.sha }}