name: CD Pipeline


on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
      - "release/*"  

jobs:

  # ======================
  # 1. BUILD BACKEND
  # ======================
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build backend image
        run: |
          docker build \
            -f apps/backend/dockerfile \
            -t dangwminh/backend:${{ github.sha }} \
            apps/backend

      - name: Push backend image
        run: |
          docker push dangwminh/backend:${{ github.sha }}


  # ======================
  # 2. BUILD FRONTEND
  # ======================
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build frontend image
        run: |
          docker build \
            -f apps/frontend/dockerfile \
            -t dangwminh/frontend:${{ github.sha }} \
            apps/frontend

      - name: Push frontend image
        run: |
          docker push dangwminh/frontend:${{ github.sha }}


  # ======================
  # 3. DEPLOY (CHỈ CHẠY KHI 2 BUILD OK)
  # ======================
  deploy:
    needs: [backend, frontend]
    runs-on: ubuntu-latest

    steps:

      # ======================
      # Checkout
      # ======================
      - name: Checkout
        uses: actions/checkout@v4

      # ======================
      # AWS config
      # ======================
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # ======================
      # Get EC2 instance
      # ======================
      - name: Get instance ID
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=swarm-manager" \
            --query "Reservations[0].Instances[0].InstanceId" \
            --output text)

          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

      # ======================
      # Check state
      # ======================
      - name: Check instance state
        run: |
          STATE=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_ID \
            --query "Reservations[0].Instances[0].State.Name" \
            --output text)

          echo "STATE=$STATE"
          echo "STATE=$STATE" >> $GITHUB_ENV

      # ======================
      # Start if stopped
      # ======================
      - name: Start instance
        if: env.STATE == 'stopped'
        run: |
          aws ec2 start-instances --instance-ids $INSTANCE_ID

      # ======================
      # Wait running
      # ======================
      - name: Wait instance running
        run: |
          STATE=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_ID \
            --query "Reservations[0].Instances[0].State.Name" \
            --output text)

          if [ "$STATE" = "terminated" ]; then
            echo "Instance terminated → stop pipeline"
            exit 1
          fi

          aws ec2 wait instance-running --instance-ids $INSTANCE_ID

      # ======================
      # Get public IP
      # ======================
      - name: Get IP
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_ID \
            --query "Reservations[0].Instances[0].PublicIpAddress" \
            --output text)

          echo "SERVER_HOST=$PUBLIC_IP" >> $GITHUB_ENV

      # ======================
      # SSH wait
      # ======================
      - name: Wait SSH
        run: |
          for i in {1..30}; do
            nc -z $SERVER_HOST 22 && echo "SSH ready" && break
            sleep 5
          done

      # ======================
      # Prepare folder
      # ======================
      - name: Prepare deploy folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/deploy
            mkdir -p /home/ubuntu/deploy/monitoring
      - name: Check files
        run: |
          pwd
          ls -lah
          ls -lah monitoring
          test -f docker-stack.yml
          test -f nginx.conf
          test -f monitoring/otel_config.yaml

      # ======================
      # Copy stack
      # ======================
      - name: Copy stack files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: |
            docker-stack.yml
            nginx.conf
            monitoring/otel_config.yaml
          target: "/home/ubuntu/deploy"
            

      # ======================
      # Deploy swarm
      # ======================
      - name: Deploy Swarm
        uses: appleboy/ssh-action@v1.0.3
        env:
          IMAGE_TAG: ${{ github.sha }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          CLOUDY_NAME: ${{ secrets.CLOUDY_NAME }}
          CLOUDY_API_KEY: ${{ secrets.CLOUDY_API_KEY }}
          CLOUDY_SECRET: ${{ secrets.CLOUDY_SECRET }}
          GG_CLIENT_ID: ${{ secrets.GG_CLIENT_ID }}

        with:
          host: ${{ env.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          envs: IMAGE_TAG,MONGODB_URI,JWT_SECRET_KEY,CLOUDY_NAME,CLOUDY_API_KEY,CLOUDY_SECRET,GG_CLIENT_ID

          script: |
            cd /home/ubuntu/deploy

            docker network inspect noteweb-net >/dev/null 2>&1 || \
              docker network create --driver overlay --attachable noteweb-net

            docker stack deploy \
              --with-registry-auth \
              -c docker-stack.yml \
              app

            docker run --rm \
              --network noteweb-net \
              -e MONGODB_URI="$MONGODB_URI" \
              -e SEED_DROP=false \
              dangwminh/backend:$IMAGE_TAG \
              python seed.py