name: Mongo CD

on:
  push:
    branches:
      - main
      - Test/cicd-test
  workflow_dispatch:

jobs:
  mongo:
    runs-on: ubuntu-latest

    steps:
      - name: "[INFO - General] Checkout"
        uses: actions/checkout@v4

      - name: "[INFO - General] Login Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: "[INFO - Mongo] Build Mongo image"
        run: |
          docker build \
            -f mongo-init/Dockerfile \
            -t dangwminh/mongo-init:${{ github.sha }} \
            ./mongo-init

      - name: "[INFO - Mongo] Push Mongo image"
        run: |
          docker push dangwminh/mongo-init:${{ github.sha }}
