name: Release

on:
  workflow_run:
    workflows:
      - "Frontend Build"
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Emit release signal
        run: echo "READY_TO_DEPLOY=${{ github.sha }}" >> $GITHUB_ENV